= Init container

The AMQ Pod consist of two containers:

* Init container
+
This init container runs an `artemis create ...` command to generate an AMQ configuration based on the parameters set in CRs. This config is recreated every time the Pod starts, that's how changes in the CRs are being applied. 
* Broker container
+
The main container runs `artemis run ...` with the config generated by the init container (at `/home/jboss/amq-broker` <?>) using the `data` and `log` directories from the persistent volume (`/opt/var/amq-data` <?>)

For the container startup scripts see https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/blob/main/modules/activemq-artemis-launch/added/launch.sh[launch.sh] in the _AMQ Broker Container Image Source Code_ downloads for the release being used.

== Custom init container

The operator supports the most common use cases, but we can't set all the configuration for the broker, we need a custom init container for advanced configuration. The source for a custom init container is simple:

----
.
├── Dockerfile
└── scripts
    └── post-config.sh
----

* *Dockerfile*: Make sure you build FROM the original init container matching your AMQ version.
+
----
FROM registry.redhat.io/amq7/amq-broker-init-rhel8:7.10-25
ADD ./scripts /amq/scripts
---- 
* *post-config.sh*: This script is called after the `artemis create` command. We can modify the generated configuration in `${CONFIG_INSTANCE_DIR}` directory.


