apiVersion: batch/v1
kind: Job
metadata:
  name: helm-amq-operator-post-delete-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: helm-amq-operator-post-delete-hook
    spec:
      restartPolicy: Never
      serviceAccountName: helm-amq-operator-post-delete-hook
      containers:
      - name: main
        image: "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest"
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          # Delete CSV, it's not removed automatically with the Subscription
          oc delete clusterserviceversion.operators.coreos.com -l operators.coreos.com/amq-broker-rhel8.{{ .Release.Namespace }}
          # Delete CSV, it may not be removed automatically with the Subscription
          oc delete installplan.operators.coreos.com -l operators.coreos.com/amq-broker-rhel8.{{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-amq-operator-post-delete-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-amq-operator-post-delete-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  - clusterserviceversions
  verbs:
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-amq-operator-post-delete-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helm-amq-operator-post-delete-hook
subjects:
- kind: ServiceAccount
  name: helm-amq-operator-post-delete-hook