{
 "title": "AMQ Broker",
 "description": "Dashboard for monitoring Apache Artemis",
 "tags": [ "apache artemis" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=~\".*\",namespace!~\".*-bld|.*monitoring|.*meta|.*dev.*|.*tst.*\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{pod=~\"$instance\",  namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))*100/sum(avg_over_time(jvm_memory_max_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))*100/sum(avg_over_time(jvm_memory_max_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker)(artemis_message_count{pod='$instance',  namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ((rate(artemis_messages_added{pod=~\"$instance\", namespace=~\"$namespace\"}[1m])) + (rate(artemis_messages_acknowledged{pod=~\"$instance\", namespace=~\"$namespace\"}[1m])))"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_disk_store_usage{pod=~\"$instance\", namespace=~\"$namespace\"} )",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - avg(kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Restart Count / 7days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$instance\"}[7d]))",
     "legendFormat": "Restart Count"
    }
   ]
  },
  {
   "title": "Operator Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace=~\"$namespace\", pod=~\"$instance\", label_rht_subcomp =~ \"broker-amq\"} unless kube_pod_labels{namespace=~\"$namespace\", pod=~\"$instance\", label_rht_coom =~ \"AMQ\"}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage (millicores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=~\"core\",namespace=~\"$namespace\",pod=~\".*$instance.*\",instance!~\".*-deploy\"}) by (namespace,pod)*1000",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=~\"core\", namespace=~\"$namespace\",pod=~\".*$instance.*\",pod!~\".*-deploy\"}) by (namespace,pod)*1000",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{namespace=~\"$namespace\",pod=~\".*$instance.*\",pod!~\".*-deploy\"}) by (namespace,pod)*1000",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=~\"byte\",namespace=~\"$namespace\",pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=~\"byte\",namespace=~\"$namespace\",pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "Heap Max"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=~\"heap\", pod=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "Heap Usage"
    },
    {
     "expr": "sum by (broker) (artemis_address_memory_usage{pod=~\"$instance\",  namespace=~\"$namespace\"})",
     "legendFormat": "Global Max Usage"
    }
   ]
  },
  {
   "title": "Message Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (rate(artemis_messages_added{pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Producing"
    },
    {
     "expr": "sum by (broker) (rate(artemis_messages_acknowledged{pod=~\"$instance\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Consuming"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_connection_count{pod=~\"$instance\",  namespace=~\"$namespace\"} )",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "sum by (address) ( topk (20, artemis_consumer_count{pod=~\"$instance\",  namespace=~\"$namespace\"} ) )",
     "legendFormat": "{{address}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_message_count{pod=~\"$instance\",  namespace=~\"$namespace\"})",
     "legendFormat": "{{broker}}"
    },
    {
     "expr": "sum by (queue) ( topk (20, artemis_message_count{pod=~\"$instance\",  namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"} ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Persistent Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_persistent_size{pod=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{broker}}"
    },
    {
     "expr": "sum by (queue) ( topk (20, artemis_persistent_size{pod=~\"$instance\", namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"} ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Produced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_added{pod=~\"$instance\", namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"}[1m]) ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_acknowledged{pod=~\"$instance\", namespace=~\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"}[1m]) ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Expired",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_expired{pod=~\"$instance\", namespace=~\"$namespace\"}[1m]) ) )",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_disk_store_usage{pod=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Paging",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_number_of_pages{pod=~\"$instance\", namespace=~\"$namespace\"} )",
     "legendFormat": "{{broker}}"
    },
    {
     "expr": "sum by (address) ( topk (20, artemis_number_of_pages{pod=~\"$instance\", namespace=~\"$namespace\"} ) )",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}