= Troubleshooting

== Heap dump

To get a heap dump inside the container we can use `jcmd 1 GC.heap_dump /opt/my-broker/data/heap.hprof` or `jmap -dump:format=b,file=/opt/my-broker/data/heap.hprof 1`, then we can `oc cp...` the file over:

----
HEAP_FILE=heap_$(date +%F-%H-%M).hprof
# Create
oc exec my-broker-ss-0 -- jcmd 1 GC.heap_dump /opt/my-broker/data/$HEAP_FILE
# List, check size
oc exec my-broker-ss-0 -- ls -las /opt/my-broker/data/
# Copy
oc cp my-broker-ss-0:/opt/my-broker/data/$HEAP_FILE ./$HEAP_FILE
# Delete
oc exec my-broker-ss-0 -- rm /opt/my-broker/data/$HEAP_FILE
----

== Thread dump

Similarly we can get a thread dump with `jcmd 1 Thread.print`:

----
oc exec my-broker-ss-0 -- jcmd 1 Thread.print
----

== Attach debugger

To connect an IDE debugger to AMQ broker running in container, we need to enable remote debugging and `oc port-forward...` the port.

We need to add debugging parameters to the JVM `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005`:

* This can be done with a custom init container modifying `artemis.profile`, like 
+
----
echo 'JAVA_ARGS="$JAVA_ARGS -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"' >>${CONFIG_INSTANCE_DIR}/etc/artemis.profile
----
* Or simply by adding environment variable `JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005` to the broker's _StatefulSet_. We need to scale down the operator before this, otherwise it will reset the changes.

The Java process will wait until we attach a debugger to the process, make sure the `livenessProbe.initialDelaySeconds` is set to high. 

Port forward the "5005" port to your local machine `oc port-forward my-broker-ss-0 5005:5005` and connect with an IDE (e.g. IntelliJ) that has the broker's source code open to `localhost:5005`.

== Critical analyzer

If the critical analyzer causes unexpected - false alarm - restarts, it can be disabled in the _broker.xml_ or with _brokerProperties_: 

```
  brokerProperties:
    - criticalAnalyzer=false
```

We can verify if the analyzer is running by looking for a thread `Thread-0 (-scheduled-threads)` or by enabling TRACE logging:

```
# In running Pod:
sed -i 's/logger.org.apache.activemq.artemis.utils.critical.level=.*/logger.org.apache.activemq.artemis.utils.critical.level=TRACE/' /home/jboss/amq-broker/etc/logging.properties
sed -i 's/handler.CONSOLE.level=.*/handler.CONSOLE.level=TRACE/' /home/jboss/amq-broker/etc/logging.properties
```

It periodically drops a line like:
`TRACE [org.apache.activemq.artemis.utils.critical.CriticalAnalyzer] Checking critical analyzer`

== TLS1.0

AMQ v7.10 runs on JDK17, which has TLSv1.0 and TLSv1.1 disabled. If a client can't support TLSv1.2 (e.g. https://activemq.apache.org/components/nms/providers/activemq/[Apache.NMS.ActiveMQ] v1.6), we may have to re-enable TLSv1.0 in the JDK, by overwriting the default `java.security` file:

Add something like this to the init container:
```
# Create security file with "TLSv1" and  "TLSv1.1" removed from disabledAlgorithms
cat >${CONFIG_INSTANCE_DIR}/etc/java.security <<EOF
security.useSystemPropertiesFile=false
jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL
EOF

# Use security file to overwrite default values. Optionally add "-Djavax.net.debug=all" to see `supported_versions (43)`
echo '\nJAVA_ARGS="$JAVA_ARGS -Djava.security.properties=/home/jboss/amq-broker/etc/java.security"' >>${CONFIG_INSTANCE_DIR}/etc/artemis.profile
```

[NOTE]
The `acceptor.enabledProtocols` value doesn't seem to have an impact on the available TLS versions.